namePrefix: '{{ include "chart.fullname" . }}-'

namespace: '{{ .Release.Namespace | quote }}'

generatorOptions:
  disableNameSuffixHash: true

  # Trick so kustomize does not split the annotation value
commonAnnotations:
  cert-manager.io/inject-ca-from: '{{.Release.Namespace}}/{{. | include "chart.fullname"}}-serving-cert'


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../webhook
patches:
- path: validatingwebhook_endpoint_patch.yaml
- path: mutatingwebhook_endpoint_patch.yaml
