apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- storage.yaml
- ../../kustomizeconfig
- ../harborcluster-minimal


labels:
- includeSelectors: true
  pairs:
    sample: "true"
patches:
- path: harbor_chartmuseum_patch.yaml
- path: harbor_notary_patch.yaml
- path: harbor_portal_patch.yaml
- path: harbor_trivy_patch.yaml
