apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- literals:
  - redis-password=the-redis-password
  name: harbor-redis
  type: goharbor.io/redis
labels:
- includeSelectors: true
  pairs:
    sample: "true"
