apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add resources section to bring in the deployment you want to patch
resources:
- ../../config/default  # Adjust this path to where your deployment is defined

patches:
- path: patches-image-source.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: harbor-operator