namePrefix: '{{ include "chart.fullname" . }}-'

namespace: '{{ .Release.Namespace | quote }}'

generatorOptions:
  disableNameSuffixHash: true


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../certmanager
patches:
- path: patch_certificate_dns.yaml
- path: patch_certificate_secret.yaml
