apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - init-db.sql
  name: harbor-init-db

secretGenerator:
- literals:
  - postgres-password=the-database-password
  name: harbor-database-password
  type: goharbor.io/postgresql
labels:
- includeSelectors: true
  pairs:
    sample: "true"
